[project]
name = "yieldbox"
authors = []
description = "DeFi Yield Farming Vaults on Stacks"
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[contracts.yieldbox]
path = "contracts/yieldbox.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
